const store = require('../data/store');

const sampleArtifacts = [
  {
    id: 'art-1',
    name: 'Dhokra Bastar Brass Deity',
    category: 'Metal Crafts',
    community: 'Dokra Damar',
    village: 'Dokra Village',
    district: 'Bastar',
    state: 'Chhattisgarh',
    historicalPeriod: 'Ancient (techniques dating to Indus Valley Civilization)',
    origin: 'Bastar Forest Region',
    materials: ['Brass', 'Beeswax', 'Clay core', 'Bronze scrap'],
    dimensions: '12 x 5 x 4 inches',
    weight: '1.8 kg',
    description: 'A traditional lost-wax cast brass figurine representing a local forest deity, handcrafted using ancient clay cores and fine beeswax thread moldings. The surface shows the characteristic thread-like textures typical of Bastar metalwork.',
    culturalSignificance: 'Acts as a spiritual guardian of the village and fields. These figurines are typically offered to local shrines to pray for healthy crops and livestock.',
    symbolicMeaning: 'The vertical posture represents high spiritual alignment, and the hand gestures signify blessings and protective aura.',
    traditionalUsage: 'Ritual offerings during community harvest festivals and installation in tribal home shrines.',
    associatedFestivals: ['Bastar Lokotsav', 'Bastar Dussehra', 'Madi Festival'],
    associatedStories: ['The Legend of the First Metalworker', 'Bonbibi Folk Lore'],
    associatedCrafts: ['Dokra Metal Craft'],
    relatedVillages: ['Kondagaon', 'Bastar Village'],
    relatedHeritagePaths: ['path-3', 'path-6'],
    relatedNaturalSites: ['Bastar Sacred Groves'],
    preservationStatus: 'Under Threat (due to rising charcoal prices and dwindling master craftsman numbers)',
    condition: 'Excellent',
    museumNotes: 'Sourced directly from Ekta Artisan Center. Shows distinct traditional copper-rich casting alloys.',
    references: ['Coomaraswamy, A. K. (1985). "Tribal Art of Central India."', 'State Craft Registry of Chhattisgarh, 2024.'],
    imageGallery: [
      'https://images.unsplash.com/photo-1605721911519-3dfeb3be25e7?w=800&q=80',
      'https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?w=800&q=80'
    ],
    audioExplanation: '/assets/audio/dhokra_deity_explanation.mp3',
    video: 'https://www.youtube.com/embed/dQw4w9WgXcQ', // Placeholder video URL or embed
    createdAt: new Date('2026-01-10T10:00:00.000Z').toISOString(),
    updatedAt: new Date('2026-05-12T14:30:00.000Z').toISOString(),
    views: 142
  },
  {
    id: 'art-2',
    name: 'Traditional Nakshi Kantha Quilt',
    category: 'Textiles',
    community: 'Bengali Village Weavers',
    village: 'Kantha Village',
    district: 'Birbhum',
    state: 'West Bengal',
    historicalPeriod: 'Mid-20th Century (Revival Period)',
    origin: 'Rural Birbhum District',
    materials: ['Recycled Cotton Saris', 'Dyed Indigo Thread', 'Folk Red Cotton Suture'],
    dimensions: '72 x 60 inches',
    weight: '1.2 kg',
    description: 'A finely detailed hand-stitched running quilt made of multiple layers of soft old cotton saris. The intricate running stitch (Kantha) is laid out in a central lotus mandala motif with surrounding representations of village scenes and local flora.',
    culturalSignificance: 'Given as wedding gifts or to newborns, embodying wishes of warmth, safety, and long life. The layers symbolize family unity and protection.',
    symbolicMeaning: 'Central lotus symbol represents purity and spiritual birth; fish icons represent abundance, and bird patterns represent free spirit.',
    traditionalUsage: 'Bed covers, ceremonial seating wraps during festivals, and family heritage keepsakes.',
    associatedFestivals: ['Bengali New Year (Naba Barsha)', 'Durga Puja', 'Poush Mela'],
    associatedStories: ['Sari Recycling Traditions', 'The Rippling Thread of Bengal'],
    associatedCrafts: ['Kantha Embroidery'],
    relatedVillages: ['Kantha Village', 'Shantiniketan'],
    relatedHeritagePaths: ['path-1', 'path-4', 'path-6'],
    relatedNaturalSites: ['Birbhum Wetlands'],
    preservationStatus: 'Preserved (strong commercial market revival through rural self-help cooperatives)',
    condition: 'Good (some color fading on borders)',
    museumNotes: 'Donated by the Birbhum Women Craft Collective. Features authentic hand-spun indigo dyes.',
    references: ['Dutt, Gurusaday. (1990). "Folk Arts and Crafts of Bengal."', 'Birbhum Heritage Registry.'],
    imageGallery: [
      'https://images.unsplash.com/photo-1528698827591-e19ccd7bc23d?w=800&q=80',
      'https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&q=80'
    ],
    audioExplanation: '/assets/audio/kantha_quilt_story.mp3',
    video: '',
    createdAt: new Date('2026-02-15T09:12:00.000Z').toISOString(),
    updatedAt: new Date('2026-06-01T11:20:00.000Z').toISOString(),
    views: 89
  },
  {
    id: 'art-3',
    name: 'Sikki Grass ceremonial Maun Basket',
    category: 'Handcrafted Implements',
    community: 'Mithila Artisans',
    village: 'Mithila Region',
    district: 'Madhubani',
    state: 'Bihar',
    historicalPeriod: 'Late 20th Century',
    origin: 'Mithila Floodplains',
    materials: ['Wild Sikki Grass', 'Munj Grass core', 'Organic vegetable dyes'],
    dimensions: '14 x 14 x 10 inches',
    weight: '0.4 kg',
    description: 'A structural storage container made by hand-coiling golden wild river grass (Sikki) around a sturdy core of Munj grass. The exterior is decorated with colored grass weave representing local peacocks and geometric shapes.',
    culturalSignificance: 'Passed from mother to daughter during weddings to store valuable spices and dowry items, symbolizing self-reliance and household prosperity.',
    symbolicMeaning: 'The peacock motif symbolizes beauty and domestic joy. The solid coiled circular structure represents infinite lineage.',
    traditionalUsage: 'Storing grains, spices, wedding trousseau ornaments, and presenting ceremonial sweets.',
    associatedFestivals: ['Madhushravani', 'Chhath Puja', 'Saurath Mela'],
    associatedStories: ['The Golden Sheen of the Riverlands', 'Blessings of the Mithila Mothers'],
    associatedCrafts: ['Sikki Grass Craft'],
    relatedVillages: ['Madhubani Village', 'Darbhanga Village'],
    relatedHeritagePaths: ['path-5', 'path-6'],
    relatedNaturalSites: ['Baghmati River Basin'],
    preservationStatus: 'Endangered (due to loss of wild marshlands and young artisans migrating to cities)',
    condition: 'Fragile (requires humidity-controlled storage)',
    museumNotes: 'Acquired in Darbhanga district. Built using a traditional bone needle (Takua) tool.',
    references: ['Jha, N. K. (2010). "Grass Weaving of North Bihar."', 'National Institute of Design Monograph.'],
    imageGallery: [
      'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=800&q=80',
      'https://images.unsplash.com/photo-1590736969955-71cb91d3176d?w=800&q=80'
    ],
    audioExplanation: '',
    video: '',
    createdAt: new Date('2026-03-20T14:00:00.000Z').toISOString(),
    updatedAt: new Date('2026-03-20T14:00:00.000Z').toISOString(),
    views: 45
  },
  {
    id: 'art-4',
    name: 'Kathputli Puppet (Raja Harishchandra)',
    category: 'Indigenous Objects',
    community: 'Bhatt Community',
    village: 'Jodhpur',
    district: 'Jodhpur',
    state: 'Rajasthan',
    historicalPeriod: 'Early 20th Century',
    origin: 'Marwar Deserts',
    materials: ['Mango wood block', 'Starch-stiffened Cotton', 'Gold tinsel ribbon'],
    dimensions: '24 x 6 x 4 inches',
    weight: '0.6 kg',
    description: 'A traditional Rajasthani string puppet representing the legendary king Harishchandra. The head is sculpted from a single piece of mango wood and painted with expressive large eyes, dressed in royal Rajasthani court costume.',
    culturalSignificance: 'Maintains oral records of history and morality, bringing epic stories to life through theater in villages where literacy rates were historically low.',
    symbolicMeaning: 'Large eyes reflect divine sight and pure truthfulness. The bright red costume represents courage and royalty.',
    traditionalUsage: 'Traveling puppet shows, local folk theatre acts, and educational morality plays.',
    associatedFestivals: ['Marwar Festival', 'Kabir Yatra', 'Pushkar Camel Fair'],
    associatedStories: ['The Legend of Truthful King Harishchandra', 'Court Stories of Mewar'],
    associatedCrafts: ['Kathputli Puppetry'],
    relatedVillages: ['Jodhpur Village', 'Jaipur Colony'],
    relatedHeritagePaths: ['path-4', 'path-6'],
    relatedNaturalSites: ['Thar Desert Heritage Zone'],
    preservationStatus: 'Under Threat (loss of performance venues due to digital media domination)',
    condition: 'Good (textile elements restored)',
    museumNotes: 'Sourced from a traditional puppeteer family in Jodhpur. Strings show traditional hemp bindings.',
    references: ['Samar, Devi Lal. (1980). "Folk Entertainment of Rajasthan."', 'Bhartiya Lok Kala Mandal Archives.'],
    imageGallery: [
      'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&q=80',
      'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&q=80'
    ],
    audioExplanation: '/assets/audio/puppetry_morality_play.mp3',
    video: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    createdAt: new Date('2026-04-05T16:45:00.000Z').toISOString(),
    updatedAt: new Date('2026-04-10T09:15:00.000Z').toISOString(),
    views: 110
  },
  {
    id: 'art-5',
    name: 'Madhubani Kohbar Ritual Painting',
    category: 'Ceremonial Objects',
    community: 'Mithila Women Artists',
    village: 'Madhubani Village',
    district: 'Madhubani',
    state: 'Bihar',
    historicalPeriod: 'Late 20th Century',
    origin: 'Mithila Region',
    materials: ['Handmade paper (cow-dung treated)', 'Bamboo twigs', 'Mineral colors'],
    dimensions: '22 x 30 inches',
    weight: '0.1 kg',
    description: 'A traditional Kohbar painting created using plant and mineral pigments on paper treated with a cow-dung wash. The Kohbar features a central bamboo tree surrounded by lotus leaves, fish, and birds in dense geometric compositions.',
    culturalSignificance: 'Kohbar is the central ritual painting created in the wedding chamber of a new couple to symbolize fertility, love, and community blessings.',
    symbolicMeaning: 'The bamboo tree represents long life and masculine lineage, while the lotus flower represents feminine purity and fertility. Fish denote abundance.',
    traditionalUsage: 'Decorating marriage chambers, celebrating weddings, and offering ritual prayers for household peace.',
    associatedFestivals: ['Chhath Puja', 'Mithila Utsav', 'Vivah Panchami'],
    associatedStories: ['The Union of Shiva and Parvati', 'Tales of the Forest Trees'],
    associatedCrafts: ['Madhubani Paintings'],
    relatedVillages: ['Madhubani Village', 'Ranti Village'],
    relatedHeritagePaths: ['path-2', 'path-6'],
    relatedNaturalSites: ['Kamla River Ghats'],
    preservationStatus: 'Preserved',
    condition: 'Excellent',
    museumNotes: 'Signed by Master Artisan Meera Devi. Utilizes natural soot for all black borders.',
    references: ['Archer, W. G. (1973). "Mithila Painting."', 'Mithila Art Research Center Publications.'],
    imageGallery: [
      'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=800&q=80',
      'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&q=80'
    ],
    audioExplanation: '',
    video: '',
    createdAt: new Date('2026-05-01T11:00:00.000Z').toISOString(),
    updatedAt: new Date('2026-06-15T15:20:00.000Z').toISOString(),
    views: 205
  }
];

function initializeSampleArtifactData() {
  sampleArtifacts.forEach(art => {
    store.artifacts.push(art);
  });
  console.log(`✅ Loaded ${store.artifacts.length} sample cultural artifacts.`);
}

module.exports = initializeSampleArtifactData;
